cc_library(
    name = "list",
    hdrs = [
    	"list.h",
    ],
    srcs = [
    	"list.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
    	"//src/main/c/com/micromouse/maze",
    ],
)