cc_library(
    name = "hardware",
    hdrs = [
    	"hardware.h",
    ],
    srcs = [
    	"hardware.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/c/com/micromouse/utility/direction",
    ],
)