cc_library(
    name = "maze",
    hdrs = [
    	"maze.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/cc/maze/cell",
    ],
    linkopts = ["-std=c++11"],
    copts = ["-isystemsrc/main/cc"],
)
