cc_test(
    name = "location",
    srcs = ["LocationTests.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//src/main/c/com/micromouse/location",
    ],
)