cc_test(
    name = "vector",
    srcs = ["VectorTests.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//src/main/c/com/micromouse/utility/vector",
    ],
)