cc_library(
    name = "cell",
    hdrs = [
    	"cell.h",
    ],
    srcs = [
    	"cell.cc",
    ],
    visibility = ["//visibility:public"],
    linkopts = ["-std=c++11"],
    copts = ["-isystemsrc/main/cc"],
)
