cc_library(
    name = "robot",
    hdrs = [
    	"robot.h",
    ],
    srcs = [
    	"robot.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
    	"//src/main/c/com/micromouse/location",
        "//src/main/c/com/micromouse/maze",
        "//src/main/c/com/micromouse/utility/direction",
        "//src/main/c/com/micromouse/utility/list",
        "//src/main/c/com/micromouse/hardware",
    ],
)
