cc_library(
    name = "maze",
    hdrs = [
    	"cell.h",
    ],
    srcs = [
    	"cell.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
    	"//src/main/c/com/micromouse/location",
    ],
)
