cc_library(
    name = "vector",
    hdrs = [
    	"cell_vector.h",
    ],
    srcs = [
    	"cell_vector.c",
    ],
    visibility = ["//visibility:public"],
    deps = [
    	"//src/main/c/com/micromouse/maze",
    ],
)